### ISSUE TITLE
fortify

### ISSUE THREAD

**Issue by TatianaBurek** [dtcenter/METviewer#108]
Fixing fortify issues

**Comment by TatianaBurek** [comment]
Remove password parameter from DatabaseInfo class.
Pass it to the functions as a separate function parameter

**Comment by TatianaBurek** [comment]
MysqlLoadDatabaseManager - replace SQL injection with parameterized SQL statements

**Comment by TatianaBurek** [comment]
MVServlet - remove redirect

**Comment by TatianaBurek** [comment]
MySqlDatabaseManager - use connection.setCatalog() instead of "use database"

**Comment by TatianaBurek** [comment]
Start working on issue:
Cross-Site Scripting  MVServlet.java line 1168
Proposed solution: instead of using SrtingBuffer to create XML response use javax.xml library

**Comment by TatianaBurek** [comment]
Use MVUtil.cleanString method on each filename string to avoid "Path Manipulation" Fortify category

**Comment by hankenstein2** [comment]
We don't use Fortify anymore, transitioned to STIGS and be
