### ISSUE TITLE
Revision series for MODE-TD

### ISSUE THREAD

**Issue by TatianaBurek** [dtcenter/METviewer#111]

**Comment by TressaFowler** [comment]
Revisions must be calculated separately for each object using the 2d MTD output data. They make the most sense for area and intensity percentiles (10,25,50,75,90). These values cannot be accumulated for many objects (e.g. medians of 2 objects of different size cannot be estimated from this data.)

(Perhaps the centroid shifting in x direction or y direction would also make sense, but this has not been considered or tested so I am not sure yet.)

Once the revision data are calculated, the Wald Wolfowitz statistic and the autocorrelation statistic can be calculated. Time series plots probably won't work, but box plots of revisions, perhaps divided up by lead time or valid hour, are interesting. An example is attached.

![RevisionBoxplots](https://user-images.githubusercontent.com/33267910/62723597-4b587280-b9ce-11e9-85bf-86f84eb88ea0.jpeg)

**Comment by TatianaBurek** [comment]
[Revision History manual.pdf](https://github.com/dtcenter/METviewer/files/5440648/Revision.History.manual.pdf)
