### ISSUE TITLE
CTC line type from MET v11.0.0 cannot be inserted to METviewer

### ISSUE THREAD

**Issue by daniel-lagrava-spire** [dtcenter/METviewer#447]
## Describe the Problem ##
CTC line type had 15 columns for files generated with MET v10.X:
VERSION MODEL DESC FCST_LEAD FCST_VALID_BEG  FCST_VALID_END  OBS_LEAD OBS_VALID_BEG   OBS_VALID_END   FCST_VAR FCST_UNITS FCST_LEV OBS_VAR OBS_UNITS OBS_LEV OBTYPE VX_MASK INTERP_MTHD INTERP_PNTS FCST_THRESH OBS_THRESH COV_THRESH ALPHA LINE_TYPE TOTAL FY_OY FY_ON FN_OY FN_ON

Since MET v11.0.0, there is an additional column (EC_VALUE) as it can be seen here: https://met.readthedocs.io/en/latest/Users_Guide/point-stat.html?highlight=EC_VALUE#id7

When trying to load those sort of files using `mv_load_mv_load.sh` the parser crashes:
```
edu.ucar.metviewer.DatabaseException: caught SQLException calling executeBatch: (conn=25) Could not set parameter at position 16 (values was '0.5')
Query - conn:25(M)  - "INSERT INTO line_data_ctc VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)"
```

### Expected Behavior ###
CTC files from MET v11.0.0 can be inserted on METviewer ie. it can consume rows with 16 columns.

### Environment ###
Describe your runtime environment:
Local install of METviewer v4.1.0 using Docker. However, by inspecting the METviewer code for the latest realease (or even main), the CTC line type is still set to 15 columns.

### To Reproduce ###
Describe the steps to reproduce the behavior:
Try to generate and insert any CTC file with MET v11.0.0 and try to insert it. A one line example:
```
VERSION MODEL DESC FCST_LEAD FCST_VALID_BEG  FCST_VALID_END  OBS_LEAD OBS_VALID_BEG   OBS_VALID_END   FCST_VAR FCST_UNITS FCST_LEV OBS_VAR OBS_UNITS OBS_LEV OBTYPE VX_MASK INTERP_MTHD INTERP_PNTS FCST_THRESH OBS_THRESH COV_THRESH ALPHA LINE_TYPE TOTAL FY_OY FY_ON FN_OY FN_ON EC_VALUE
V11.0.0 TEST  NA   060000    20221008_060000 20221010_060000 000000   20221008_055500 20221010_055500 QOP6Hr   kg/m^2     A6       APCP_06 kg/m^2    A06     ADPSFC K0E0    NEAREST     1           >0          >0         NA         NA    CTC           3     1     0     2     0      0.5
```

Thanks for your help with this issue!

**Comment by bikegeek** [comment]
Requestor created this in the wrong project.  Will close.
